version: "3"
services:
  app:
    build:
      context: .
    command: /bin/sh -c "composer install && php test.php"
    volumes:
      - .:/app:delegated
    depends_on:
      - emulator
  emulator:
    image: gcr.io/cloud-spanner-emulator/emulator
